# Generated by Django 5.2.8 on 2026-03-21 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_lesson_order_alter_module_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated completion time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='Markdown list of what learners will achieve'),
        ),
        migrations.AddField(
            model_name='module',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='module_thumbnails/'),
        ),
        migrations.AddField(
            model_name='module',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='modules', to='content.tag'),
        ),
    ]
